version: '3.3'
services:
    web-dvwa:
        ports:
            - '8880:80'
        image: vulnerables/web-dvwa

    phpldapadmin-remote-dump:
        ports:
            - '8881:80'
        image: vulnerables/phpldapadmin-remote-dump

    cve-2014-6271:
        ports:
            - '8082:80'
        image: vulnerables/cve-2014-6271

    cve-2014-0160:
        ports:
            - '8443:443'
        image: vulnerables/cve-2014-0160

    coldfusion:
        image: vulhub/coldfusion:8.0.1
        ports:
            - "8500:8500"

    web:
        image: vulhub/phpmyadmin:4.8.1
        volumes:
            - ./config.inc.php:/var/www/html/config.inc.php
        ports:
            - "8083:80"
        depends_on:
            - mysql

    mysql:
        image: mysql:5.5
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=test
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test

    juice-shop:
        ports:
            - '3000:3000'
        image: bkimminich/juice-shop

    dsvw:
        ports:
            - '8000:8000'
        image: appsecco/dsvw

    webgoat:
        ports:
            - '8080:8080'
            - '9090:9090'
        environment:
            - TZ=America/Denver
        image: webgoat/webgoat

    tufts-ctf-fall2014:
        container_name: ctf
        ports:
            - '80:80'
        image: mchow01/tufts-ctf-fall2014
    badstore-docker:
        ports:
            - '8086:80'
        image: jvhoof/badstore-docker
